### ISSUE TITLE
dm_afhq_model.pth

### ISSUE THREAD

**Issue by Sourabs-kms** [steven202/semantic_adv_via_dm#7]
Hello, I would like to ask about the weight of dm_afhq_model.pth in the code part of training main_afhq_train.py in your code, but there is no relevant pth file in the materials you provided, please provide the relevant file, thank you very much！

**Comment by steven202** [comment]
For afhq, as stated in the appendix of the paper, we can only generate dog images. 
We use model weights from https://github.com/gwang-kim/DiffusionCLIP.
